name: common_simple
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-149.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  postgres: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

